<?php

namespace App\Services;

class Business
{
    public function get()
    {
        return [
            'AUTOBUSES Y TRACTOCAMIONES DE QUERETARO' => 'AUTOBUSES Y TRACTOCAMIONES DE QUERETARO',
            'SOLUCIONES INTEGRALES PARA TU CAMION SOCASA (TOLUCA)' => 'SOLUCIONES INTEGRALES PARA TU CAMION SOCASA (TOLUCA)',
            'SOLUCIONES INTEGRALES PARA TU CAMION SOCASA (REFACCIONARIA)' => 'SOLUCIONES INTEGRALES PARA TU CAMION SOCASA (REFACCIONARIA)',
            'SOLUCIONES INTEGRALES PARA TU CAMION SOCASA (XONA)' => 'SOLUCIONES INTEGRALES PARA TU CAMION SOCASA (XONA)',
            'SOLUCIONES INTEGRALES PARA TU CAMION SOCASA (STAFF)' => 'SOLUCIONES INTEGRALES PARA TU CAMION SOCASA (STAFF)',
        ];
    }
}
